version: "3"
services:
  server:
    container_name: notice-board
    build:
      context: . #notice-board
      dockerfile: Dockerfile
    # env_file: .env
    depends_on:
      - postgres-database
    networks:
      - main_bridge
    ports:
    - "3000:50001"
  postgres-database:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    restart: always
    #env_file:
      #- .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-database:/var/lib/postgresql/data
    networks:
      - main_bridge
    
volumes:
  server:
  postgres-database:


# Networks to be created to facilitate communication between containers
networks:
  main_bridge:
    driver: bridge